version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
      build: .
      container_name: app
      ports:
        - "3000:3000"
      depends_on:
        - mongodb
      environment:
        - MONGODB_URI=mongodb://mongo:27017/tester              

volumes:
  mongodb_data:
